window:
  padding:
    x: 10
    y: 10
  dimensions:
    columns: 90 
    lines: 25 
  opacity: 0.7
scrolling:
  history: 100000
  multiplier: 3
font:
  normal:
    family: "Menlo for Powerline"
    style: Regular
  bold:
    family: "Menlo for Powerline"
    style: Bold
  italic:
    family: "Menlo for Powerline"
    style: Italic
  bold_italic:
    family: "Menlo for Powerline"
    style: Bold Italic
  size: 11.0
  draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: Space,  mods: Control|Shift, mode: ~Search,    action: ToggleViMode            }
  - { key: P,  mode: Vi|~Search,    action: Paste            }
